### ISSUE TITLE
Main commit 06a85d3 is Not working

### ISSUE THREAD

**Issue by trojan-uma** [nihedon/sd-webui-weight-helper#8]
Right click has no response.

Error info (from chrome devtools)
![Snipaste_2024-07-07_16-07-18](https://github.com/nihedon/sd-webui-weight-helper/assets/33084797/c98a9010-abf4-4c69-ba7d-ce9af91d4ba4)
![Snipaste_2024-07-07_16-07-29](https://github.com/nihedon/sd-webui-weight-helper/assets/33084797/edd5a309-7de0-4b20-9bf4-e7bed583e89a)
![Snipaste_2024-07-07_16-07-37](https://github.com/nihedon/sd-webui-weight-helper/assets/33084797/fd9dd257-d56c-41fc-9554-6c25e33a2e83)

PS:commit 885770a is the last working version.

**Comment by nihedon** [comment]
@trojan-uma 
Thank you for reporting the bug.

Due to the increasing complexity of the context menu's DOM tree, we've transitioned to using templates to construct the DOM tree in the new version. These templates are fetched from the server, which might cause communication before the WebUI initialization completes, potentially resulting in failures.

We've made changes to retry the communication in case of failures. Could you please try the latest version(2933d84) and let us know if the issue persists? Thank you!

**Comment by trojan-uma** [comment]
No, but error info was changed

New error info (just show in software opening)
![Snipaste_2024-07-08_07-45-26](https://github.com/nihedon/sd-webui-weight-helper/assets/33084797/589ebecd-ab7b-4aca-a1db-90e026f09879)

**Comment by nihedon** [comment]
@trojan-uma 
It looks like the error is occurring in the section that retrieves the change history. There might be corruption in the localStorage data, so we've adjusted it to prevent errors even if the data is corrupted. Please update to the latest version(e3924e8) and check again.

PS: out of the three screenshots you initially provided, the second one shows an error in "civitai_helper.js," which is unrelated to this extension.

**Comment by trojan-uma** [comment]
> @trojan-uma It looks like the error is occurring in the section that retrieves the change history. There might be corruption in the localStorage data, so we've adjusted it to prevent errors even if the data is corrupted. Please update to the latest version([e3924e8](https://github.com/nihedon/sd-webui-weight-helper/commit/e3924e8f2dad3160b3d2b3412e386fa8455c7be0)) and check again.
> 
> PS: out of the three screenshots you initially provided, the second one shows an error in "civitai_helper.js," which is unrelated to this extension.

commit e3924e8 is working!!! thx
